description: ConvertOpenImagesToCOCO

target:
  service: amlk8s
  name: itpeastusv100cl
  vc: resrchvc

environment:
  image: joshins/pytorch:1.7.0-cuda11.0-cudnn8-devel-wsdetr
  setup:
   - pip install -r openimages_to_coco/requirements.txt
  
code:
  local_dir: $CONFIG_DIR/

data:
  remote_dir: data/

jobs:
- name: ConvertOpenImagesToCOCO
  sku: G1
  command:
  - python openimages_to_coco/convert_openimages.py -p $$PT_DATA_DIR/openimages
