description: DeformableDETR_FGVC

target:
  service: amlk8s
  name: itpscusv100cl
  vc: resrchvc

environment:
  image: joshins/pytorch:1.7.0-cuda11.0-cudnn8-devel-wsdetr
  setup:
   - pip install -r requirements.txt
   - sh make.sh
  
code:
  local_dir: $CONFIG_DIR/

storage:
  cvgroupsouthcentral:
    storage_account_name: cvgroupsouthcentral
    container_name: datasets

jobs:
- name: DeformableDETR_FGVC
  sku: G4
  command:
  - GPUS_PER_NODE=4 ./tools/run_dist_launch.sh 4 ./configs/pt.sh --train_imgs_dir /mnt/cvgroupsouthcentral/fgvc-aircraft-2013b/images --train_anns /mnt/cvgroupsouthcentral/fgvc-aircraft-2013b/annotations/trainval.json --val_imgs_dir /mnt/cvgroupsouthcentral/fgvc-aircraft-2013b/images --val_anns /mnt/cvgroupsouthcentral/fgvc-aircraft-2013b/annotations/test.json --frozen_weights /mnt/cvgroupsouthcentral/ckpts/detreg.pth --batch_size 2 --num_classes 101 --epochs 50 --lr_drop 40 --output_dir /mnt/cvgroupsouthcentral/ckpts/fgvc

- name: DeformableDETR_FGVC_OneClass
  sku: G4
  command:
  - GPUS_PER_NODE=4 ./tools/run_dist_launch.sh 4 ./configs/pt.sh --train_imgs_dir /mnt/cvgroupsouthcentral/fgvc-aircraft-2013b/images --train_anns /mnt/cvgroupsouthcentral/fgvc-aircraft-2013b/annotations/trainval_oneclass.json --val_imgs_dir /mnt/cvgroupsouthcentral/fgvc-aircraft-2013b/images --val_anns /mnt/cvgroupsouthcentral/fgvc-aircraft-2013b/annotations/test_oneclass.json --frozen_weights /mnt/cvgroupsouthcentral/ckpts/detreg.pth --batch_size 2 --num_classes 2 --epochs 50 --lr_drop 40 --output_dir /mnt/cvgroupsouthcentral/ckpts/fgvc_oneclass
