description: DeformableDETR_FSOD

target:
  service: amlk8s
  name: itpscusv100cl
  vc: resrchvc

environment:
  image: joshins/pytorch:1.7.0-cuda11.0-cudnn8-devel-wsdetr
  setup:
   - pip install -r requirements.txt
   - sh make.sh
  
code:
  local_dir: $CONFIG_DIR/

storage:
  cvgroupsouthcentral:
    storage_account_name: cvgroupsouthcentral
    container_name: datasets

jobs:
- name: DeformableDETR_FSOD
  sku: G8
  command:
  - GPUS_PER_NODE=8 ./tools/run_dist_launch.sh 8 ./configs/pt.sh --train_imgs_dir /mnt/cvgroupsouthcentral/fsod/images --train_anns /mnt/cvgroupsouthcentral/fsod/annotations/fsod_train.json --val_imgs_dir /mnt/cvgroupsouthcentral/fsod/images --val_anns /mnt/cvgroupsouthcentral/fsod/annotations/fsod_train.json --frozen_weights /mnt/cvgroupsouthcentral/ckpts/detreg.pth --batch_size 2 --num_classes 800 --epochs 50 --lr_drop 40 --output_dir /mnt/cvgroupsouthcentral/ckpts/fsod

- name: DeformableDETR_FSOD_OneClass
  sku: G8
  command:
  - GPUS_PER_NODE=8 ./tools/run_dist_launch.sh 8 ./configs/pt.sh --train_imgs_dir /mnt/cvgroupsouthcentral/fsod/images --train_anns /mnt/cvgroupsouthcentral/fsod/annotations/fsod_train_oneclass.json --val_imgs_dir /mnt/cvgroupsouthcentral/fsod/images --val_anns /mnt/cvgroupsouthcentral/fsod/annotations/fsod_test_oneclass.json --frozen_weights /mnt/cvgroupsouthcentral/ckpts/detreg.pth --batch_size 2 --num_classes 800 --epochs 50 --lr_drop 40 --output_dir /mnt/cvgroupsouthcentral/ckpts/fsod_oneclass
