description: DeformableDETR_FSOD

target:
  service: amlk8s
  name: itpscusv100cl
  vc: resrchvc

environment:
  image: joshins/pytorch:1.7.0-cuda11.0-cudnn8-devel-wsdetr
  setup:
   - pip install -r requirements.txt
   - sh make.sh

code:
  local_dir: $CONFIG_DIR/

storage:
  cvgroupsouthcentral:
    storage_account_name: cvgroupsouthcentral
    container_name: datasets

jobs:
- name: DeformableDETR_FSOD_Finetune_MultiMulti
  sku: G8
  command:
  - GPUS_PER_NODE=8 ./tools/run_dist_launch.sh 8 ./configs/pt.sh --train_imgs_dir /mnt/cvgroupsouthcentral/fsod/images --train_anns /mnt/cvgroupsouthcentral/fsod/annotations/fsod_200_train.json --val_imgs_dir /mnt/cvgroupsouthcentral/fsod/images --val_anns /mnt/cvgroupsouthcentral/fsod/annotations/fsod_200_test.json --frozen_weights /mnt/cvgroupsouthcentral/ckpts/fsod_800_train/checkpoint0049.pth --batch_size 2 --num_classes 201 --epochs 50 --lr_drop 40 --output_dir /mnt/cvgroupsouthcentral/ckpts/fsod_200_finetune_multi_multi --lr 1e-4 --lr_backbone 1e-5 --no_eval

- name: DeformableDETR_FSOD_Finetune_MultiOne
  sku: G8
  command:
  - GPUS_PER_NODE=8 ./tools/run_dist_launch.sh 8 ./configs/pt.sh --train_imgs_dir /mnt/cvgroupsouthcentral/fsod/images --train_anns /mnt/cvgroupsouthcentral/fsod/annotations/fsod_200_train_oneclass.json --val_imgs_dir /mnt/cvgroupsouthcentral/fsod/images --val_anns /mnt/cvgroupsouthcentral/fsod/annotations/fsod_200_test_oneclass.json --frozen_weights /mnt/cvgroupsouthcentral/ckpts/fsod_800_train/checkpoint0049.pth --batch_size 2 --num_classes 2 --epochs 50 --lr_drop 40 --output_dir /mnt/cvgroupsouthcentral/ckpts/fsod_200_finetune_multi_one --lr 1e-4 --lr_backbone 1e-5 --no_eval

- name: DeformableDETR_FSOD_Finetune_OneMulti
  sku: G8
  command:
  - GPUS_PER_NODE=8 ./tools/run_dist_launch.sh 8 ./configs/pt.sh --train_imgs_dir /mnt/cvgroupsouthcentral/fsod/images --train_anns /mnt/cvgroupsouthcentral/fsod/annotations/fsod_200_train.json --val_imgs_dir /mnt/cvgroupsouthcentral/fsod/images --val_anns /mnt/cvgroupsouthcentral/fsod/annotations/fsod_200_test.json --frozen_weights /mnt/cvgroupsouthcentral/ckpts/fsod_800_train_oneclass/checkpoint0049.pth --batch_size 2 --num_classes 201 --epochs 50 --lr_drop 40 --output_dir /mnt/cvgroupsouthcentral/ckpts/fsod_200_finetune_one_multi --lr 1e-4 --lr_backbone 1e-5 --no_eval

- name: DeformableDETR_FSOD_Finetune_OneOne
  sku: G8
  command:
  - GPUS_PER_NODE=8 ./tools/run_dist_launch.sh 8 ./configs/pt.sh --train_imgs_dir /mnt/cvgroupsouthcentral/fsod/images --train_anns /mnt/cvgroupsouthcentral/fsod/annotations/fsod_200_train_oneclass.json --val_imgs_dir /mnt/cvgroupsouthcentral/fsod/images --val_anns /mnt/cvgroupsouthcentral/fsod/annotations/fsod_200_test_oneclass.json --frozen_weights /mnt/cvgroupsouthcentral/ckpts/fsod_800_train_oneclass/checkpoint0049.pth --batch_size 2 --num_classes 2 --epochs 50 --lr_drop 40 --output_dir /mnt/cvgroupsouthcentral/ckpts/fsod_200_finetune_one_one --lr 1e-4 --lr_backbone 1e-5 --no_eval
