description: DeformableDETR_FSOD

target:
  service: amlk8s
  name: itphyperdgx2cl2
  vc: hcrr06

environment:
  image: joshins/pytorch:1.7.0-cuda11.0-cudnn8-devel-wsdetr
  setup:
   - pip install -r requirements.txt
   - sh make.sh
  
code:
  local_dir: $CONFIG_DIR/

storage:
  cvgroupsouthcentral:
    storage_account_name: cvgroupsouthcentral
    container_name: datasets

jobs:
- name: DeformableDETR_FSOD_Finetune0
  sku: G16
  command:
  - GPUS_PER_NODE=16 ./tools/run_dist_launch.sh 16 ./configs/pt.sh --train_imgs_dir /mnt/cvgroupsouthcentral/fsod/images --train_anns /mnt/cvgroupsouthcentral/fsod/annotations/fsod_200_train0.json --val_imgs_dir /mnt/cvgroupsouthcentral/fsod/images --val_anns /mnt/cvgroupsouthcentral/fsod/annotations/fsod_200_test0.json --frozen_weights /mnt/cvgroupsouthcentral/ckpts/fsod/checkpoint0049.pth --batch_size 2 --num_classes 201 --epochs 25 --lr_drop 20 --output_dir /mnt/cvgroupsouthcentral/ckpts/fsod_finetune0

- name: DeformableDETR_FSOD_Finetune1
  sku: G16
  command:
  - GPUS_PER_NODE=16 ./tools/run_dist_launch.sh 16 ./configs/pt.sh --train_imgs_dir /mnt/cvgroupsouthcentral/fsod/images --train_anns /mnt/cvgroupsouthcentral/fsod/annotations/fsod_200_train1.json --val_imgs_dir /mnt/cvgroupsouthcentral/fsod/images --val_anns /mnt/cvgroupsouthcentral/fsod/annotations/fsod_200_test1.json --frozen_weights /mnt/cvgroupsouthcentral/ckpts/fsod/checkpoint0049.pth --batch_size 2 --num_classes 201 --epochs 25 --lr_drop 20 --output_dir /mnt/cvgroupsouthcentral/ckpts/fsod_finetune1

- name: DeformableDETR_FSOD_Finetune2
  sku: G16
  command:
  - GPUS_PER_NODE=16 ./tools/run_dist_launch.sh 16 ./configs/pt.sh --train_imgs_dir /mnt/cvgroupsouthcentral/fsod/images --train_anns /mnt/cvgroupsouthcentral/fsod/annotations/fsod_200_train2.json --val_imgs_dir /mnt/cvgroupsouthcentral/fsod/images --val_anns /mnt/cvgroupsouthcentral/fsod/annotations/fsod_200_test2.json --frozen_weights /mnt/cvgroupsouthcentral/ckpts/fsod/checkpoint0049.pth --batch_size 2 --num_classes 201 --epochs 25 --lr_drop 20 --output_dir /mnt/cvgroupsouthcentral/ckpts/fsod_finetune2

- name: DeformableDETR_FSOD_FGVC_Finetune
  sku: G16
  command:
  - GPUS_PER_NODE=16 ./tools/run_dist_launch.sh 16 ./configs/pt.sh --train_imgs_dir /mnt/cvgroupsouthcentral/fgvc-aircraft-2013b/images --train_anns /mnt/cvgroupsouthcentral/fgvc-aircraft-2013b/annotations/trainval.json --val_imgs_dir /mnt/cvgroupsouthcentral/fgvc-aircraft-2013b/images --val_anns /mnt/cvgroupsouthcentral/fgvc-aircraft-2013b/annotations/test.json --frozen_weights /mnt/cvgroupsouthcentral/ckpts/fsod/checkpoint0049.pth --batch_size 2 --num_classes 101 --epochs 25 --lr_drop 20 --output_dir /mnt/cvgroupsouthcentral/ckpts/fsod_fgvc_finetune
