description: DeformableDETR_OpenImages_NoCOCO_OneClass_DETReg

target:
  service: amlk8s
  name: itpscusv100cl
  vc: resrchvc
  
environment:
  image: joshins/pytorch:1.7.0-cuda11.0-cudnn8-devel-wsdetr
  setup:
   - pip install -r requirements.txt
   - sh make.sh
  
code:
  local_dir: $CONFIG_DIR/

storage:
  objectnet:
    storage_account_name: cvgroupsouthcentral
    container_name: datasets

jobs:
  name: DeformableDETR_OpenImages_NoCOCO_OneClass_DETReg
  sku: G8
  command:
  - GPUS_PER_NODE=8 ./tools/run_dist_launch.sh 8 ./configs/pt.sh --train_imgs_dir /mnt/objectnet/openimages/train --train_anns /mnt/objectnet/openimages/annotations/openimages_v6_nococo_train_bbox_oneclass.json --val_imgs_dir /mnt/objectnet/openimages/val --val_anns /mnt/objectnet/openimages/annotations/openimages_v6_nococo_val_bbox_oneclass.json --frozen_weights /mnt/objectnet/ckpts/detreg.pth --batch_size 32 --num_classes 2 --epochs 20 --lr_drop 16 --output_dir /mnt/objectnet/ckpts/nococo_oneclass_detreg
