description: DeformableDETR_OpenImages_NoVOC_3M

target:
  service: amlk8s
  name: itpscusv100cl
  vc: resrchvc

environment:
  image: joshins/pytorch:1.7.0-cuda11.0-cudnn8-devel-wsdetr
  setup:
   - pip install -r requirements.txt
   - sh make.sh
  
code:
  local_dir: $CONFIG_DIR/

storage:
  objectnet:
    storage_account_name: cvgroupsouthcentral
    container_name: datasets

jobs:
- name: DeformableDETR_OpenImages_NoVOC_3M
  sku: G8
  command:
  - GPUS_PER_NODE=8 ./tools/run_dist_launch.sh 8 ./configs/pt.sh --train_imgs_dir /mnt/objectnet/openimages/train --train_anns /mnt/objectnet/openimages/annotations/openimages_v6_novoc_3M_train_bbox.json --val_imgs_dir /mnt/objectnet/openimages/val --val_anns /mnt/objectnet/openimages/annotations/openimages_v6_novoc_val_bbox.json --frozen_weights /mnt/objectnet/ckpts/detreg.pth --batch_size 2 --num_classes 602 --epochs 50 --lr_drop 40 --output_dir /mnt/objectnet/ckpts/novoc_3M
